{{- $distro := .distro -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install base packages
    packages:
      - init
      - initramfs-tools
      - sudo

  - action: apt
    description: Install firmwares
    packages:
{{ if eq $distro "debian"}}
      - firmware-linux
      - firmware-realtek
{{ else if eq $distro "ubuntu"}}
      - linux-firmware
{{ end }}
  
  - action: apt
    description: Install system utilities
    packages:
      - apt-utils
      - bash-completion
      - bc
      - binutils
      - cloud-initramfs-growroot
      - curl
      - file
      - gpg
      - haveged
      - less
      - locales
      - man-db
      - python-is-python3
      - python3
      - python3-pip
      - software-properties-common
      - ssh
      - sysfsutils
      - systemd-timesyncd
      - tmux
      - u-boot-tools
      - vim
      - wget
      - whiptail
      - xz-utils
      - zram-tools

  - action: apt
    description: Install network utilities
    packages:
      - ldnsutils
      - ifupdown
      - iproute2
      - iputils-ping
      - network-manager


  - action: apt
    description: Install hardware utilities
    packages:
      - gpiod
      - i2c-tools
      - mtd-utils
      - pciutils
      - rfkill
      - spi-tools
      - usbutils

  - action: apt
    description: Install Radxa backported packages
    packages:
      - u-boot-menu

  - action: apt
    description: Install Radxa packages
    packages:
      - radxa-firmware
      - rsetup
      - radxa-otgutils
      - radxa-bootutils
