{{- $distro := .distro -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install LXQt specific packages
    packages:
      - bluedevil
      - gnome-themes-extra
      - lightdm
      - oxygen-icon-theme
      - papirus-icon-theme
      - qterminal
{{ if eq $distro "debian" }}
      - task-lxqt-desktop
{{ else }}
      - lxqt
{{ end }}

  - action: recipe
    description: Install common desktop packages
    recipe: .desktop.yaml
    variables:
      distro: {{ $distro }}
