{{- $distro := .distro -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: recipe
    description: Install CLI packages
    recipe: cli.yaml
    variables:
      distro: {{ $distro }}

  - action: apt
    description: Install sway packages
    packages:
      - sway
      - foot
