{{- $distro := .distro -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install Xfce specific packages
    packages:
      - blueman
{{ if eq $distro "debian" }}
      - task-xfce-desktop
{{ else }}
      - xfce4
{{ end }}
      - xfce4-terminal

  - action: recipe
    description: Install common desktop packages
    recipe: .desktop.yaml
    variables:
      distro: {{ $distro }}
