name: Build images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore

jobs:
  query:
    runs-on: ubuntu-22.04
    outputs:
      boards: ${{ steps.query.outputs.boards }}
      suites: ${{ steps.query.outputs.suites }}
      flavors: ${{ steps.query.outputs.flavors }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Query available board configs
        id: query
        run: |
          echo "boards=$(./rbuild json boards)" >> $GITHUB_OUTPUT
          echo "suites=$(./rbuild json suites)" >> $GITHUB_OUTPUT
          echo "flavors=$(./rbuild json flavors)" >> $GITHUB_OUTPUT

  build-rootfs:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: [ rootfs ]
        suites: ${{ fromJSON(needs.query.outputs.suites )}}
        flavors: ${{ fromJSON(needs.query.outputs.flavors )}}
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: radxa-repo/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          artifacts: true

  build-images:
    needs: [ query, build-rootfs ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: ${{ fromJSON(needs.query.outputs.boards) }}
        suites: ${{ fromJSON(needs.query.outputs.suites )}}
        flavors: ${{ fromJSON(needs.query.outputs.flavors )}}
        exclude:
          - boards: rootfs
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: radxa-repo/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          artifacts: true
          prebuilt-rootfs: true
